#!/bin/sh
sleep 30

#Re-apply rules - Force gaming ports to VOICE Tin for CAKE QoS
awk '{print $1, $2, $3}' /jffs/scripts/cake-speedsync/qosports 2>/dev/null | while read -r qosparm; do
   css_pkt_qos "$qosparm"
done 

#Run speedtest and apply cake settings
cd /jffs/scripts/cake-speedsync || exit 1
./cake-speedsync.sh

#Re-adjust cake settings every 2 hours past 7 am
#Delete cron job to avoid duplicate
cru d cake-speedsync
#Re-add cron job
cru a cake-speedsync "0 7-23/2 * * * /jffs/scripts/cake-speedsync/cake-speedsync.sh"

#Re-apply .ashrc and .profile
cp -f /jffs/scripts/cake-speedsync/.ashrc /tmp/home/root/
cp -f /jffs/scripts/cake-speedsync/.profile /tmp/home/root/